---
name: scale_y_continuous
permalink: ggplot2/scale-y/
redirect_from: ggplot2/scale_y_continuous/
description: How to use logarithmic scales with ggplot2 axes.
layout: base
thumbnail: thumbnail/log.jpg
language: ggplot2
page_type: example_index
display_as: layout_opt
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```



### Version Check

Version 4 of Plotly's R package is now [available](https://plot.ly/r/getting-started/#installation)!<br>
Check out [this post](http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/) for more information on breaking changes and new features available in this version.

```{r}
library(plotly)
packageVersion('plotly')
```

## Basic

```{r}
library(plotly)

p <- ggplot(diamonds, aes(color, log10(price))) +
    geom_boxplot() +
    scale_y_continuous("Price, log10-scaling")

p <- ggplotly(p)

p
```
Inspired by <a href="http://stackoverflow.com/questions/4699493/transform-only-one-axis-to-log10-scale-with-ggplot2">Stack Overflow</a>.
