---
name: stat_smooth
permalink: ggplot2/stat_smooth/
description: Add a smoothed line in ggplot2 and R with stat_smooth.
layout: base
thumbnail: thumbnail/stat_smooth.jpg
language: ggplot2
page_type: example_index
display_as: statistical
order: 7
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Basic

```{r}
library(plotly)

fig <-  ggplot(mpg, aes(displ, hwy))
fig <-  p + geom_point() + stat_smooth()

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://docs.ggplot2.org/current/">ggplot2 documentation</a>

### Trend Lines

```{r}
library(plotly)

x <- 1:10
y <- jitter(x^2)

DF <- data.frame(x, y)

fig <-  ggplot(DF, aes(x = x, y = y)) + geom_point() +
    stat_smooth(method = 'lm', aes(colour = 'linear'), se = FALSE) +
    stat_smooth(method = 'lm', formula = y ~ poly(x,2), aes(colour = 'polynomial'), se= FALSE) +
    stat_smooth(method = 'nls', formula = y ~ a * log(x) +b, aes(colour = 'logarithmic'), se = FALSE, start = list(a=1,b=1)) +
    stat_smooth(method = 'nls', formula = y ~ a*exp(b *x), aes(colour = 'Exponential'), se = FALSE, start = list(a=1,b=1))

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://stackoverflow.com/questions/15102254/how-do-i-add-different-trend-lines-in-r">Stack Oveflow</a>

### Facetgrid

```{r}
library(plotly)

x <- rnorm(100)
y <-  + .7*x + rnorm(100)
f1 <- as.factor(c(rep("A",50),rep("B",50)))
f2 <- as.factor(rep(c(rep("C",25),rep("D",25)),2))
df <- data.frame(cbind(x,y))
df$f1 <- f1
df$f2 <- f2

fig <-  ggplot(df,aes(x=x,y=y)) +
    geom_point() +
    facet_grid(f1~f2) +
    stat_smooth(method="lm")

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://stackoverflow.com/questions/12572035/adding-a-regression-line-to-a-facet-grid-with-qplot-in-r">Stack Overflow</a>

### Add Legend

```{r}
library(plotly)
set.seed(123)

x <- rnorm(1000)
y1 <- 2*x + rnorm(1000)
y2 <- x^2 + rnorm(1000)

ds <- data.frame(data = x, 
                 Linear = y1, 
                 Quadratic = y2)


cols1 <- c("#ff8080", "#66b3ff")
cols2 <- c("#ff4d4d", "#3399ff")

fig <-  ggplot(ds, aes(x = data)) + 
  geom_point(aes(y = Linear, color = "Linear"), size = 2, alpha = 0.5) + 
  geom_point(aes(y = Quadratic, color = "Non Linear"), size = 2, alpha = 0.5) + 
  stat_smooth(aes(x = data, y = Linear, linetype = "Linear Fit"), method = "lm", formula = y ~ x, se = F, size = 0.25, color = cols2[1]) + 
  stat_smooth(aes(x = data, y = Quadratic, linetype = "Quadratic Fit"), method = "lm", formula = y ~ poly(x,2), se = F, size = 0.25, color = cols2[2]) + 
  scale_color_manual(name = "Relationship", values = c(cols1[1], cols1[2])) + 
  scale_linetype_manual(name = "Fit Type", values = c(2, 2)) + 
  ggtitle("Manual Legend for Stat Smooth")

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://stackoverflow.com/questions/17148679/construct-a-manual-legend-for-a-complicated-plot">Stack Overflow</a>

