---
name: Axis Text
permalink: ggplot2/axis-text/
description: How to modify axis titles in R and ggplot2.
layout: base
thumbnail: thumbnail/theme_image.png
language: ggplot2
page_type: example_index
display_as: layout_opt
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Axis Text Size

```{r}
library(plotly)
set.seed(123)

df <- diamonds[sample(1:nrow(diamonds), size = 1000),]

fig <-  ggplot(df, aes(carat, price, color = color, alpha = cut)) + 
  geom_point() + 
  theme(axis.text.x = element_text(colour = "#ff6666", size = 20), 
        axis.text.y = element_text(colour = "#668cff", size = 20))
  
fig <-  ggplotly(p)

fig
```

### Axis Text Blank

```{r}
library(plotly)
set.seed(123)

df <- diamonds[sample(1:nrow(diamonds), size = 1000),]

fig <-  ggplot(df, aes(carat, price, color = cut)) + 
  geom_point() + 
  theme(axis.text = element_blank())

fig <-  ggplotly(p)

fig
```

### Vertical Text

```{r}
library(plotly)

lab <- paste("Vertical Label", c(1, 2, 3, 4, 5))

ds <- data.frame(x = sample(lab, size = 1000, replace = T),
                 y = sample(LETTERS[1:5], size = 1000, replace = T))

fig <-  ggplot(ds, aes(x = x, fill = y)) + 
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  ggtitle("Vertical Axis Labels")

fig <-  ggplotly(p)

fig
```

### Angled Text

```{r}
library(plotly)

lab <- paste("Angle Label", c(1, 2, 3, 4, 5))

ds <- data.frame(x = sample(lab, size = 1000, replace = T),
                 y = sample(LETTERS[1:5], size = 1000, replace = T))

fig <-  ggplot(ds, aes(x = x, fill = y)) + 
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 45)) + 
  ggtitle("Angle Axis Labels")

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://docs.ggplot2.org/current/">ggplot2 documentation</a>
