---
name: aes
permalink: ggplot2/aes/
description: How assign aesthetics in ggplot2 and R.
layout: base
thumbnail: thumbnail/aesthetics_image.png
language: ggplot2
page_type: example_index
display_as: layout_opt
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Fill

```{r}
library(plotly)

ds <- data.frame(x = 1:10,
                 y = sample(10:30, size = 10),
                 group = LETTERS[1:2])

# Use the fill aesthetic to specify the fill color for the bars
fig <-  ggplot(ds, aes(x, y)) +
  geom_bar(aes(fill = group), stat = "identity") +
  ggtitle("Filled bar chart")

fig <-  ggplotly(p)

fig
```

### Group

```{r}
library(plotly)

x1 <- 1:100
x2 <- x1 + 100
x3 <- x2 + 100

x <-  c(x1, x2, x3)
y <- c(2*x1, 5*x2, -2*x3)

groufig <-  c(rep("A", length(x1)),
           rep("B", length(x2)),
           rep("C", length(x3)))

ds <- data.frame(x, y, group)

# Use the group aesthetic to ensure lines are drawn separately for each group
fig <-  ggplot(ds, aes(x, y)) +
  geom_line(aes(group = group, color = group), size = 2) +
  ggtitle("Group specific line chart")

fig <-  ggplotly(p)

fig
```

### Label

```{r}
library(plotly)

ds <- data.frame(x = rnorm(10),
                 y = rnorm(10),
                 group = LETTERS[1:2])

fig <-  ggplot(ds, aes(x, y)) +
  geom_point(aes(color = group), size = 7) +
  geom_text(aes(label = group), size = 4) +
  ggtitle("Annotation with labels")

fig <-  ggplotly(p)

fig
```

### Shape

```{r}
library(plotly)

ds <- data.frame(x = letters[1:5],
                 y = rnorm(20),
                 group = LETTERS[1:4])

# Use aes shape to map individual points and or different groups to different shapes
fig <-  ggplot(ds, aes(x, y)) +
  geom_point(aes(color = group, shape = group), size = 5) +
  geom_line(aes(group = group, linetype = group)) +
  ggtitle("Groupwise shapes and line types")

fig <-  ggplotly(p)

fig
```

Inspired by <a href="http://docs.ggplot2.org/current/">ggplot2 documentation</a>
