---
name: axis.title
permalink: ggplot2/axis-title/
description: How to modify axis titles in R and ggplot2.
layout: base
thumbnail: thumbnail/theme_image.png
language: ggplot2
page_type: example_index
display_as: layout_opt
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Axis Labels

```{r}
library(plotly)
set.seed(123)

df <- diamonds[sample(1:nrow(diamonds), size = 1000),]

# To set x-axis and y-axis labels use labs()
fig <-  ggplot(df, aes(carat, price)) + 
  geom_point() + 
  labs(title = "Diamonds", x = "x-axis -> Carat", y = "y-axis -> Price")

fig <-  ggplotly(p)

# Alternatively use
fig <-  ggplot(df, aes(carat, price)) + 
  geom_point() + 
  ggtitle("Diamonds") + 
  xlab("x-axis -> Carat") + 
  ylab("y-axis -> Price")

fig <-  ggplotly(p)

fig
```

### Axis Title Size

```{r}
library(plotly)
set.seed(123)

df <- diamonds[sample(1:nrow(diamonds), size = 1000),]

fig <-  ggplot(df, aes(carat, price)) +
  geom_point() + 
  labs(title = "Diamonds", x = "x-axis -> Carat", y = "y-axis -> Price") +
  theme(plot.title = element_text(size = 50),  
        axis.title.x = element_text(size = 20),  
        axis.title.y = element_text(size = 20))  

fig <-  ggplotly(p)

fig
```

### Axis Title Colors

```{r}
library(plotly)
set.seed(123)

df <- diamonds[sample(1:nrow(diamonds), size = 1000),]

fig <-  ggplot(df, aes(carat, price)) +
  geom_point() + 
  labs(title = "Diamonds", x = "x-axis -> Carat", y = "y-axis -> Price") +
  theme(plot.title = element_text(size = 50, colour = "#668cff"),  
        axis.title.x = element_text(size = 20, colour = "#6699ff"),  
        axis.title.y = element_text(size = 20, colour = "#ff8080"))  

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://docs.ggplot2.org/current/">ggplot2 documentation</a>
