---
name: facet_wrap
permalink: ggplot2/facet_wrap/
description: How to make subplots with facet_wrap in ggplot2 and R.
layout: base
thumbnail: thumbnail/facet_wrap.jpg
language: ggplot2
page_type: example_index
display_as: layout_opt
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Basic Columns

```{r}
library(reshape2)
library(plotly)

fig <-  ggplot(tips, aes(x=total_bill, y=tip/total_bill)) + geom_point(shape=1)

# Divide by day, going horizontally and wrapping with 2 columns
fig <-  p + facet_wrap( ~ day, ncol=2)

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://www.cookbook-r.com/Graphs/Scatterplots_(ggplot2)/">Cookbook for R</a>

### Add Unique Curves

```{r}
library(plotly)

## read in data set (tolerance data from the ALDA book)
tolerance <- read.table("https://stats.idre.ucla.edu/wp-content/uploads/2016/02/tolerance1_pp.txt",
    sep = ",", header = TRUE)

## change id and male to factor variables
tolerance <- within(tolerance, {
    id <- factor(id)
    male <- factor(male, levels = 0:1, labels = c("female", "male"))
})


fig <-  ggplot(data = tolerance, aes(x = time, y = tolerance)) + geom_point() +
    stat_smooth(method = "lm", se = FALSE) + facet_wrap(~id)

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://www.ats.ucla.edu/stat/r/faq/growth.htm">The IDRE at UCLA</a>

### Add Stat_Smooth

```{r}
library(plotly)

fig <-  ggplot(mpg, aes(displ, hwy))+
  geom_point()+
  stat_smooth()+
  facet_wrap(~year)

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://www.ling.upenn.edu/~joseff/rstudy/summer2010_ggplot2_intro.html">R Study Group</a>

### Labels

```{r}
library(plotly)
set.seed(123)

df <- diamonds[sample(1:nrow(diamonds), size = 1000), ]

# Create labels
labs <- c("Best","Second best","Third best","Average", "Average","Third Worst","Second Worst","Worst")
levels(df$clarity) <- rev(labs)

fig <-  ggplot(df, aes(carat, price)) + 
  geom_point() + 
  facet_wrap(~ clarity)

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://stackoverflow.com/questions/3472980/ggplot-how-to-change-facet-labels">Stack Overflow</a>

### Titles

```{r}
library(plotly)
set.seed(123)

df <- diamonds[sample(1:nrow(diamonds), size = 1000), ]

# Create labels
labs <- c("Best","Second best","Third best","Average", "Average","Third Worst","Second Worst","Worst")
levels(df$clarity) <- rev(labs)

fig <-  ggplot(df, aes(carat, price)) + 
  geom_point() + 
  facet_wrap(~ clarity) + 
  ggtitle("Diamonds dataset facetted by clarity")

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://docs.ggplot2.org/current/">ggplot2 Documentation</a>

### Ordered Facets

```{r}
library(plotly)
set.seed(123)

df <- diamonds[sample(1:nrow(diamonds), size = 1000), ]

# Reorer levels

levels(df$clarity) <- c("VS2", "VS1", "VVS2", "I1", "SI2", "IF", "VVS1", "SI1")

fig <-  ggplot(df, aes(carat, price)) + 
  geom_point() + 
  facet_wrap(~ clarity) + 
  ggtitle("Diamonds dataset facetted by clarity")

fig <-  ggplotly(p)

fig
```
Inspired by <a href="http://stackoverflow.com/questions/3311901/how-do-i-get-ggplot-to-order-facets-correctly">Stack Overflow</a>
