---
name: interactive tooltip
permalink: ggplot2/interactive-tooltip/
description: How to add custom tooltip effects to R and ggplot2 charts with JavaScript.
layout: base
thumbnail: thumbnail/hover.jpg
language: ggplot2
page_type: example_index
display_as: layout_opt
redirect_from: ggplot2/maps/
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Maps

```{r}
library(plotly)

data(canada.cities, package="maps")
fig <-  ggplot(canada.cities, aes(long, lat)) +
        borders(regions="canada", name="borders") +
        coord_equal() +
        geom_point(aes(text=name, size=pop), colour="red", alpha=1/2, name="cities")

fig <-  ggplotly(p)

fig
```


### Custom Tooltip

```{r}
library(plotly)
#install.packages("gapminder")
library(gapminder)

fig <-  ggplot(gapminder, aes(x = gdpPercap, y = lifeExp, color = continent, text =      paste("country:", country))) +
     geom_point(alpha = (1/3)) + scale_x_log10()  
  
fig <-  ggplotly(p)

fig
```
Inspired by <a href="https://github.com/jennybc/ggplot2-tutorial/blob/master/gapminder-ggplot2-scatterplot.md">Gapminder Tutorial</a>

### Control Events

```{r}
library(plotly)
#install.packages("gapminder")
library(gapminder)

fig <-  ggplot(gapminder, aes(x = year, y = lifeExp, text = paste("country:",country))) + 
     geom_point() +
     facet_wrap(~ continent) 

fig <-  ggplotly(p)

fig
```
Inspired by <a href="https://github.com/jennybc/ggplot2-tutorial/blob/master/gapminder-ggplot2-scatterplot.md">Gapminder Tutorial</a>
