---
name: Extending ggplotly
permalink: ggplot2/extending-ggplotly/
description: How modify the plotly object after ggplot2 conversion.
layout: base
thumbnail: thumbnail/extending_ggplotly.png
language: ggplot2
page_type: example_index
display_as: fundamentals
order: 1
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Modify with Style

```{r}
library(plotly)

p <- ggplot(fortify(forecast::gold), aes(x, y)) + geom_line()

fig <- ggplotly(p)

fig <- style(fig, line = list(color = 'gold'), hoverinfo = "y", traces = 1)

fig
```

### Modify with Build

```{r}
library(plotly)

p <- ggplot(fortify(forecast::gold), aes(x, y)) + geom_line()

fig <- ggplotly(p)

fig <- plotly_build(fig)

fig$x$data[[1]]$line$color <- 'blue'

fig
```

### Modify with LayerData

```{r}
library(plotly)

p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
   geom_point() + geom_smooth()

fig <- fig %>%
  ggplotly(layerData = 2, originalData = F) %>%
  add_fun(function(p) {
    fig %>% slice(which.max(se)) %>%
      add_segments(x = ~x, xend = ~x, y = ~ymin, yend = ~ymax) %>%
      add_annotations("Maximum uncertainty", ax = 60)
  }) %>%
  add_fun(function(p) {
    fig %>% slice(which.min(se)) %>%
      add_segments(x = ~x, xend = ~x, y = ~ymin, yend = ~ymax) %>%
      add_annotations("Minimum uncertainty")
  })

fig
```

### Reference
For more information concerning modidfying the plotly object see [The Plotly Book](https://plotly-book.cpsievert.me/extending-ggplotly.html)
