---
name: geom_rug
permalink: ggplot2/geom_rug/
description: How to use geom_rug with Plotly.
layout: base
thumbnail: thumbnail/geom_rug.jpg
language: ggplot2
page_type: example_index
display_as: basic
order: 10
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Basic Example

```{r}
library(plotly)

df <- MASS::birthwt

df <- with(df, {
  race <- factor(race, labels = c("white", "black", "other"))
  ptd <- factor(ptl > 0)
  ftv <- factor(ftv)
  levels(ftv)[-(1:2)] <- "2+"
  data.frame(low = factor(low), age, lwt, race, smoke = (smoke > 0),
             ptd, ht = (ht > 0), ui = (ui > 0), ftv, bwt)
})

fig <-  ggplot(df, aes(lwt, bwt, colour = smoke)) +
  geom_point(size = 1) +
  geom_rug()

fig <-  ggplotly(p)

fig
```
Reference: [ggplot2 docs](http://ggplot2.tidyverse.org/reference/geom_rug.html#examples)

### Reference

See [https://plot.ly/r/reference](https://plot.ly/r/reference) for more information and options!
