---
name: Histograms
permalink: ggplot2/histograms/
description: How to make Histogram Plots in ggplot2 with Plotly.
layout: base
thumbnail: thumbnail/histogram.jpg
language: ggplot2
page_type: u-guide
display_as: statistical
order: 3
redirect_from: ggplot2/histograms/
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Basic Histogram

```{r}
library(plotly)

dat <- data.frame(xx = c(runif(100,20,50),runif(100,40,80),runif(100,0,30)),yy = rep(letters[1:3],each = 100))

p <- ggplot(dat,aes(x=xx)) +
    geom_histogram(data=subset(dat,yy == 'a'),fill = "red", alpha = 0.2) +
    geom_histogram(data=subset(dat,yy == 'b'),fill = "blue", alpha = 0.2) +
    geom_histogram(data=subset(dat,yy == 'c'),fill = "green", alpha = 0.2)

ggplotly(p)
```

### Add Lines

```{r}
library(plotly)

df1 <- data.frame(cond = factor( rep(c("A","B"), each=200) ),
                  rating = c(rnorm(200),rnorm(200, mean=.8)))

df2 <- data.frame(x=c(.5,1),cond=factor(c("A","B")))

p <- ggplot(data=df1, aes(x=rating, fill=cond)) +
    geom_vline(xintercept=c(.5,1)) +
    geom_histogram(binwidth=.5, position="dodge")

ggplotly(p)
```

### Add Facet

```{r}
library(plotly)

df <- data.frame (type=rep(1:2, each=1000), subtype=rep(c("a","b"), each=500), value=rnorm(4000, 0,1))

library(plyr)
df.text<-ddply(df,.(type,subtype),summarise,mean.value=mean(value))

p <- ggplot(df, aes(x=value, fill=subtype)) +
    geom_histogram(position="identity", alpha=0.4)+
    facet_grid(. ~ type)

ggplotly(p)
```

### Probability & Density

```{r}
library(plotly)

df <- data.frame(x = rnorm(1000))

p <- ggplot(df, aes(x=x)) +
    geom_histogram(aes(y = ..density..), binwidth=density(df$x)$bw) +
    geom_density(fill="red", alpha = 0.2)

ggplotly(p)
```
