---
name: Hover Text and Formatting
permalink: ggplot2/hover-text-and-formatting/
description: How to use hover text and formatting in ggplot2 with Plotly.
layout: base
thumbnail: thumbnail/hover-text.png
language: ggplot2
page_type: u-guide
display_as: base
order: 23
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Maps

```{r}
library(plotly)

data(canada.cities, package="maps")
p <- ggplot(canada.cities, aes(long, lat)) +
        borders(regions="canada", name="borders") +
        coord_equal() +
        geom_point(aes(text=name, size=pop), colour="red", alpha=1/2, name="cities")

ggplotly(p)
```


### Custom Tooltip

```{r}
library(plotly)
#install.packages("gapminder")
library(gapminder)

p <- ggplot(gapminder, aes(x = gdpPercap, y = lifeExp, color = continent, text =      paste("country:", country))) +
     geom_point(alpha = (1/3)) + scale_x_log10()  
  
ggplotly(p)
```
Inspired by <a href="https://github.com/jennybc/ggplot2-tutorial/blob/master/gapminder-ggplot2-scatterplot.md">Gapminder Tutorial</a>

### Control Events

```{r}
library(plotly)
#install.packages("gapminder")
library(gapminder)

p <- ggplot(gapminder, aes(x = year, y = lifeExp, text = paste("country:",country))) + 
     geom_point() +
     facet_wrap(~ continent) 

ggplotly(p)
```
Inspired by <a href="https://github.com/jennybc/ggplot2-tutorial/blob/master/gapminder-ggplot2-scatterplot.md">Gapminder Tutorial</a>
