---
name: Map Subplots And Small Multiples
permalink: r/map-subplots-and-small-multiples/
description: How to create map subplots and small multiples in R.
layout: base
thumbnail: thumbnail/map-subplots.jpg
language: r
display_as: multiple_axes
order: 2
page_type: example_index
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Basic Subplots with Maps

```{r}
library(plotly)
library(dplyr)
df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/1962_2006_walmart_store_openings.csv')

# common map properties
g <- list(
  scope = 'usa',
  showland = T,
  landcolor = toRGB("gray90"),
  showcountries = F,
  subunitcolor = toRGB("white")
)

one_mafig <-  function(dat) {
  plot_geo(dat) 
fig <- fig %>%
    add_markers(x = ~LON, y = ~LAT, color = I("blue"), alpha = 0.5) 
fig <- fig %>%
    add_text(x = -78, y = 47, text = ~unique(YEAR), color = I("black")) 
fig <- fig %>%
    layout(geo = g)
}

fig <- df
fig <- fig %>% group_by(YEAR)
fig <- fig %>% do(mafig = one_map(.))
fig <- fig %>% subplot(nrows = 9)
fig <- fig %>% layout(
    showlegend = FALSE,
    title = 'New Walmart Stores per year 1962-2006<br> Source: <a href="http://www.econ.umn.edu/~holmes/data/WalMart/index.html">University of Minnesota</a>',
    width = 1000,
    height = 900,
    hovermode = FALSE
  )

fig
```
