---
name: Graphing Multiple Chart Types
permalink: r/graphing-multiple-chart-types/
description: How to design figures with multiple chart types in R. An example of a line chart with a line of best fit and an uncertainty band.
layout: base
thumbnail: thumbnail/mixed.jpg
language: r
display_as: basic
order: 11
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Bar and Line Chart

```{r}
library(plotly)

airquality_sept <- airquality[which(airquality$Month == 9),]
airquality_sept$Date <- as.Date(paste(airquality_sept$Month, airquality_sept$Day, 1973, sep = "."), format = "%m.%d.%Y")

fig <- plot_ly(airquality_sept)
fig <- fig %>% add_trace(x = ~Date, y = ~Wind, type = 'bar', name = 'Wind',
            marker = list(color = '#C9EFF9'),
            hoverinfo = "text",
            text = ~paste(Wind, ' mph'))
fig <- fig %>% add_trace(x = ~Date, y = ~Temp, type = 'scatter', mode = 'lines', name = 'Temperature', yaxis = 'y2',
            line = list(color = '#45171D'),
            hoverinfo = "text",
            text = ~paste(Temp, '°F'))
fig <- fig %>% layout(title = 'New York Wind and Temperature Measurements for September 1973',
         xaxis = list(title = ""),
         yaxis = list(side = 'left', title = 'Wind in mph', showgrid = FALSE, zeroline = FALSE),
         yaxis2 = list(side = 'right', overlaying = "y", title = 'Temperature in degrees F', showgrid = FALSE, zeroline = FALSE))

fig
```

### Scatterplot with Loess Smoother

```{r}
library(plotly)

fig <- plot_ly(mtcars, x = ~disp, color = I("black"))
fig <- fig %>% add_markers(y = ~mpg, text = rownames(mtcars), showlegend = FALSE)
fig <- fig %>% add_lines(y = ~fitted(loess(mpg ~ disp)),
            line = list(color = '#07A4B5'),
            name = "Loess Smoother", showlegend = TRUE)
fig <- fig %>% layout(xaxis = list(title = 'Displacement (cu.in.)'),
         yaxis = list(title = 'Miles/(US) gallon'),
         legend = list(x = 0.80, y = 0.90))

fig
```

### Loess Smoother with Uncertainty Bounds

```{r}
library(plotly)
library(broom)

m <- loess(mpg ~ disp, data = mtcars)

fig <- plot_ly(mtcars, x = ~disp, color = I("black"))
fig <- fig %>% add_markers(y = ~mpg, text = rownames(mtcars), showlegend = FALSE)
fig <- fig %>% add_lines(y = ~fitted(loess(mpg ~ disp)),
            line = list(color = 'rgba(7, 164, 181, 1)'),
            name = "Loess Smoother")
fig <- fig %>% add_ribbons(data = augment(m),
              ymin = ~.fitted - 1.96 * .se.fit,
              ymax = ~.fitted + 1.96 * .se.fit,
              line = list(color = 'rgba(7, 164, 181, 0.05)'),
              fillcolor = 'rgba(7, 164, 181, 0.2)',
              name = "Standard Error")
fig <- fig %>% layout(xaxis = list(title = 'Displacement (cu.in.)'),
         yaxis = list(title = 'Miles/(US) gallon'),
         legend = list(x = 0.80, y = 0.90))

fig
```

### Plotting Forecast Objects

```{r}
library(plotly)
library(forecast)

fit <- ets(USAccDeaths)
fore <- forecast(fit, h = 48, level = c(80, 95))

fig <- plot_ly()
fig <- fig %>% add_lines(x = time(USAccDeaths), y = USAccDeaths,
            color = I("black"), name = "observed")
fig <- fig %>% add_ribbons(x = time(fore$mean), ymin = fore$lower[, 2], ymax = fore$upper[, 2],
              color = I("gray95"), name = "95% confidence")
fig <- fig %>% add_ribbons(x = time(fore$mean), ymin = fore$lower[, 1], ymax = fore$upper[, 1],
              color = I("gray80"), name = "80% confidence")
fig <- fig %>% add_lines(x = time(fore$mean), y = fore$mean, color = I("blue"), name = "prediction")

fig
```

#Reference

See [https://plot.ly/r/reference/](https://plot.ly/r/reference/) for more information and chart attribute options!
