---
description: How to use shapes in R. Two examples on highlighting regions by adding
  shapes to your R charts.
display_as: file_settings
language: r
layout: base
name: Shapes
order: 13
output:
  html_document:
    keep_md: true
page_type: u-guide
permalink: r/shapes/
thumbnail: thumbnail/shape.jpg
---

```{r, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```
### Lines

```{r}
library(plotly)

s <- seq.int(0, 15)
fig <- plot_ly(x = ~s, y = ~sin(s), mode = "lines")

# initiate a line shape object
line <- list(
  type = "line",
  line = list(color = "pink"),
  xref = "x",
  yref = "y"
)

lines <- list()
for (i in c(0, 3, 5, 7, 9, 13)) {
  line[["x0"]] <- i
  line[["x1"]] <- i + 2
  line[c("y0", "y1")] <- sin(i + 1)
  lines <- c(lines, list(line))
}

fig <- layout(p, title = 'Highlighting with Lines', shapes = lines)

fig
```

### Rectangles
```{r}
library(plotly)
fig <- plot_ly(economics, x = ~date, y = ~uempmed, name = "unemployment")

# add shapes to the layout
fig <- layout(fig, title = 'Highlighting with Rectangles',
             shapes = list(
               list(type = "rect",
                    fillcolor = "blue", line = list(color = "blue"), opacity = 0.3,
                    x0 = "1980-01-01", x1 = "1985-01-01", xref = "x",
                    y0 = 4, y1 = 12.5, yref = "y"),
               list(type = "rect",
                 fillcolor = "blue", line = list(color = "blue"), opacity = 0.2,
                 x0 = "2000-01-01", x1 = "2005-01-01", xref = "x",
                 y0 = 4, y1 = 12.5, yref = "y")))

fig
```

### Circles

Circles are centered around  ((`x0`+`x1`)/2, (`y0`+`y1`)/2))

```{r}
library(plotly)
fig <- diamonds[sample(nrow(diamonds), 1000), ]
fig <- plot_ly(fig, x = ~carat, y = ~price, text = ~paste("Clarity: ", clarity),
             mode = "markers", color = ~carat, size = ~carat)
fig <- layout(fig, title = 'Highlighting Regions with Circles',
            shapes = list(
              list(type = 'circle',
                   xref = 'x', x0 = .2, x1 = .7,
                   yref = 'y', y0 = 20, y1 = 3000,
                   fillcolor = 'rgb(50, 20, 90)', line = list(color = 'rgb(50, 20, 90)'),
                   opacity = 0.2),
              list(type = 'circle',
                   xref = 'x', x0 = .75, x1 = 1.5,
                   yref = 'y', y0 = 2500, y1 = 7500,
                   fillcolor = 'rgb(30, 100, 120)', line = list(color = 'rgb(30, 100, 120)'),
                   opacity = 0.2),
               list(type = 'circle',
                   xref = 'x', x0 = 1.6, x1 = 2.5,
                   yref = 'y', y0 = 12500, y1 = 18500,
                   fillcolor = 'rgb(90, 200, 75)', line = list(color = 'rgb(90, 200, 75)'),
                   opacity = 0.2)))

fig
```

### Reference
Check out our <b>[reference page](https://plot.ly/r/reference/#layout-shapes)</b> for more information on using shapes!