---
description: How to add LaTeX to R graphs.
display_as: file_settings
language: r
layout: base
name: LaTeX Typesetting in R Graphs
order: 12
output:
  html_document:
    keep_md: true
page_type: u-guide
permalink: r/LaTeX/
thumbnail: thumbnail/creating-and-updating-figures.png
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
#### LaTeX Typesetting


```{r}
library(plotly)
fig <- plot_ly(
    x = c(1, 2, 3, 4), 
    y = c(1, 4, 9, 16),
    name = TeX("\\alpha_{1c} = 352 \\pm 11 \\text{ km s}^{-1}"))
fig <- fig %>% add_trace(
    x = c(1, 2, 3, 4), 
    y = c(0.5, 2, 4.5, 8),
    name = TeX("\\beta_{1c} = 25 \\pm 11 \\text{ km s}^{-1}"))
fig <- fig %>% layout(
    xaxis = list(
      title = TeX("\\sqrt{(n_\\text{c}(t|{T_\\text{early}}))}")),
    yaxis = list(
      title = TeX("d, r \\text{ (solar radius)}")))
fig <- fig %>% config(mathjax = 'cdn')

fig
```

#### Reference

For more information about LaTeX, [click here](https://github.com/ropensci/plotly/blob/master/inst/examples/rmd/MathJax/index.Rmd).