---
name: Histograms
permalink: r/histograms/
description: How to make a histogram in R.
layout: base
thumbnail: thumbnail/histogram.jpg
language: r
page_type: example_index
display_as: statistical
order: 3
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
#### Basic Histogram

```{r}
library(plotly)
fig <- plot_ly(x = ~rnorm(50), type = "histogram")

fig
```

#### Normalized Histogram

```{r}
library(plotly)
fig <- plot_ly(x = ~rnorm(50),
             type = "histogram",
             histnorm = "probability")

fig
```

#### Specify Binning Function

```{r}
library(plotly)

x = c("Apples","Apples","Apples","Organges", "Bananas")
y = c("5","10","3","10","5")

fig <- plot_ly(y=y, x=x, histfunc='sum', type = "histogram")
fig <- fig %>% layout(yaxis=list(type='linear'))

fig
```

#### Horizontal Histogram

```{r}
library(plotly)
fig <- plot_ly(y = ~rnorm(50), type = "histogram")

fig
```

#### Overlaid Histograms

```{r}
fig <- plot_ly(alpha = 0.6)
fig <- fig %>% add_histogram(x = ~rnorm(500))
fig <- fig %>% add_histogram(x = ~rnorm(500) + 1)
fig <- fig %>% layout(barmode = "overlay")

fig
```

#### Stacked Histograms

```{r}
fig <- plot_ly(alpha = 0.6)
fig <- fig %>% add_histogram(x = ~rnorm(500))
fig <- fig %>% add_histogram(x = ~rnorm(500) + 1)
fig <- fig %>% layout(barmode = "overlay")

fig
```

#### Cumulative Histogram

```{r}
library(plotly)
fig <- plot_ly(x = ~rnorm(50),
             type = "histogram",
             cumulative = list(enabled=TRUE))

fig
```

### Reference

See [https://plot.ly/r/reference/#histogram](https://plot.ly/r/reference/#histogram) for more information and chart attribute options!
