---
description: How to make a heatmap in R with a matrix. Seven examples of colored and
  labeled heatmaps with custom colorscales.
display_as: scientific
language: r
layout: base
name: Heatmaps
order: 3
output:
  html_document:
    keep_md: true
page_type: example_index
permalink: r/heatmaps/
thumbnail: thumbnail/heatmap.jpg
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
#### Basic Heatmap

```{r}
library(plotly)
fig <- plot_ly(z = volcano, type = "heatmap")

fig
```


#### Categorical Axes

```{r}
m <- matrix(rnorm(9), nrow = 3, ncol = 3)
fig <- plot_ly(
	x = c("a", "b", "c"), y = c("d", "e", "f"),
	z = m, type = "heatmap"
)

fig
```

#### Sequential Colorscales: Greys

The `colors` argument understands color brewer palettes (see `RColorBrewer::brewer.pal.info` for valid names).

```{r}
fig <- plot_ly(z = volcano, colors = "Greys", type = "heatmap")

fig
```

#### Custom colorscales

The `colors` argument also accepts a color interpolation function like `colorRamp()`

```{r}
fig <- plot_ly(z = volcano, colors = colorRamp(c("red", "green")), type = "heatmap")

fig
```

Or, you can do the scaling yourself and use the colorscale attribute directly...

```{r}
vals <- unique(scales::rescale(c(volcano)))
o <- order(vals, decreasing = FALSE)
cols <- scales::col_numeric("Blues", domain = NULL)(vals)
colz <- setNames(data.frame(vals[o], cols[o]), NULL)
fig <- plot_ly(z = volcano, colorscale = colz, type = "heatmap")

fig
```