---
name: Polar Charts [legacy]
permalink: r/legacy-polar-chart/
description: How to create a polar chart in R. Three examples of polar line, polar scatter, and polar area chart.
layout: base
thumbnail: thumbnail/polar.jpg
language: r
#page_type: example_index
display_as: legacy_charts
order: 1
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```

### Legacy Plots

These polar charts are legacy and will likely be deprecated in [Plotly 2.0](https://github.com/plotly/plotly.js/issues/420). Please see the new `scatterpolar` and `scatterpolargl` [trace types](https://plot.ly/r/polar-chart/) for latest and greatest in Plotly polar coordinates.

### Polar Scatter Chart

```{r}
library(plotly)
fig <- plot_ly(
  plotly::mic, r = ~r, t = ~t, color = ~nms, alpha = 0.5, type = "scatter"
)

fig <- layout(p, title = "Mic Patterns", orientation = -90)

fig
```

```{r}
fig <- plot_ly(
  plotly::hobbs, r = ~r, t = ~t, color = ~nms, alpha = 0.5, type = "scatter"
)

fig <- layout(fig, title = "Hobbs-Pearson Trials", plot_bgcolor = toRGB("grey90"))

fig
```

### Polar Area Chart

```{r}
fig <- plot_ly(plotly::wind, r = ~r, t = ~t) %>% add_area(color = ~nms)
fig <- layout(fig, radialaxis = list(ticksuffix = "%"), orientation = 270)

fig
```

### Reference
See [https://plot.ly/python/reference/#area](https://plot.ly/python/reference/#area) for more information and chart attribute options!
