---
description: How to make a 2D histogram in R. A 2D histogram is a visualization of
  a bivariate distribution.
display_as: statistical
language: r
layout: base
name: 2D Histograms
order: 1
output:
  html_document:
    keep_md: true
page_type: example_index
permalink: r/2D-Histogram/
thumbnail: thumbnail/histogram2d.jpg
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
#### Basic 2D Histogram

2D histograms require `x`/`y`, but in contrast to heatmaps, `z` is optional. If `z` is not provided, binning occurs in the browser (see [here](https://plotly.com/r/reference/#histogram2d-histnorm) for a list of binning options).

```{r}
# install.packages('mvtnorm')
library(plotly)

s <- matrix(c(1, -.75, -.75, 1), ncol = 2)
obs <- mvtnorm::rmvnorm(500, sigma = s)
fig <- plot_ly(x = obs[,1], y = obs[,2])
fig2 <- subplot(
  fig %>% add_markers(alpha = 0.2),
  fig %>% add_histogram2d()
)

fig2
```

#### Colorscale
If `z` is not provided, the only way to control coloring is through the [colorscale attribute](https://plotly.com/r/reference/#histogram2d-colorscale)

```{r}
fig <- fig %>% add_histogram2d(colorscale = "Blues")

fig
```