---
name: WebGL in Plotly and R
permalink: r/webgl-vs-svg-time-series/
description: How to create plots using WebGL and Plotly
layout: base
language: r
page_type: example_index
output: 
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```



### Version Check

Version 4 of Plotly's R package is now [available](https://plot.ly/r/getting-started/#installation)!<br>
Check out [this post](http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/) for more information on breaking changes and new features available in this version.

```{r}
library(plotly)
packageVersion('plotly')
```

# WebGL for time series data (24381 points)

```{r}
library(plotly)
library(readr)

# Read some weather data
df <- readr::read_csv(
  'https://raw.githubusercontent.com/plotly/datasets/master/2016-weather-data-seattle.csv'
)

# Convert to dates
df$Date <- as.Date(df$Date, format =  "%m/%d/%Y")

p <- plot_ly(df, x = ~Date, y = ~Mean_TemperatureC) %>% 
  add_lines(color = I("purple")) %>%
  toWebGL() %>%
  layout(title = "Mean Temparature in Seattle (1948 - 2015)",
         yaxis = list(title = "Temperature (<sup>o</sup>C)"))

p
```
