---
description: How to embed logos and images into Plotly charts.
display_as: file_settings
language: r
layout: base
name: Embedding Logos in Plotly Graphs
order: 14
output:
  html_document:
    keep_md: true
page_type: u-guide
permalink: r/logos/
thumbnail: thumbnail/orca-management.png
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Embed Logos on a Graph

```{r}
library(plotly)

fig <- plot_ly(x = c(1, 2, 3), y = c(1, 2, 3))
fig <- fig %>% add_lines() 
fig <- fig %>%
  layout(
    images = list(
      list(source = "https://images.plot.ly/language-icons/api-home/python-logo.png",
           xref = "paper",
           yref = "paper",
           x= 0,
           y= 1,
           sizex = 0.2,
           sizey = 0.2,
           opacity = 0.8
      ),

      list(source = "https://images.plot.ly/language-icons/api-home/matlab-logo.png",
           xref = "x",
           yref = "paper",
           x = 2.7,
           y = 0.25,
           sizex = 0.4,
           sizey = 0.8,
           opacity = 0.8
      ),

      list(source =  "https://images.plot.ly/language-icons/api-home/r-logo.png",
           xref = "x",
           yref = "y",
           x = 0.9,
           y = 3.1,
           sizex = 2,
           sizey = 2,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below"
      )
    )
  )

fig
```