---
name: 3D Subplots
permalink: r/3d-subplots/
description: How to create 3D subplots in R with Plotly.
layout: base
thumbnail: thumbnail/3d-subplots.jpg
language: r
display_as: multiple_axes
order: 6
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```


### Version Check

Version 4 of Plotly's R package is now [available](https://plot.ly/r/getting-started/#installation)!<br>
Check out [this post](http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/) for more information on breaking changes and new features available in this version.
```{r}
library(plotly)
packageVersion('plotly')
```

### 3D Subplot

```{r}
library(plotly)

# custom grid style
axx <- list(
  gridcolor='rgb(255, 255, 255)',
  zerolinecolor='rgb(255, 255, 255)',
  showbackground=TRUE,
  backgroundcolor='rgb(230, 230,230)'
)

# individual plots
p1 <- plot_ly(z = ~volcano, scene='scene1') %>%
  add_surface(showscale=FALSE)

p2 <- plot_ly(z = ~volcano, scene='scene2') %>%
  add_surface(showscale=FALSE)

p3 <- plot_ly(z = ~volcano, scene='scene3') %>%
  add_surface(showscale=FALSE)

p4 <- plot_ly(z = ~volcano, scene='scene4') %>%
  add_surface(showscale=FALSE)

# subplot and define scene
p <- subplot(p1, p2, p3, p4) %>%
  layout(title = "3D Subplots",
         scene = list(domain=list(x=c(0,0.5),y=c(0.5,1)),
                      xaxis=axx, yaxis=axx, zaxis=axx,
                      aspectmode='cube'),
         scene2 = list(domain=list(x=c(0.5,1),y=c(0.5,1)),
                       xaxis=axx, yaxis=axx, zaxis=axx,
                       aspectmode='cube'),
         scene3 = list(domain=list(x=c(0,0.5),y=c(0,0.5)),
                       xaxis=axx, yaxis=axx, zaxis=axx,
                       aspectmode='cube'),
         scene4 = list(domain=list(x=c(0.5,1),y=c(0,0.5)),
                       xaxis=axx, yaxis=axx, zaxis=axx,
                       aspectmode='cube'))

p
```

#Reference

See [https://plot.ly/r/reference/#layout-scene-xaxis](https://plot.ly/r/reference/#layout-scene-xaxis) for more information and options!

