---
description: How to create font styles in R with Plotly.
display_as: file_settings
language: r
layout: base
name: Font Styles
order: 11
output:
  html_document:
    keep_md: true
page_type: u-guide
permalink: r/font/
thumbnail: thumbnail/text-and-annotations.png
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```



### Version Check

Version 4 of Plotly's R package is now [available](https://plot.ly/r/getting-started/#installation)!<br>
Check out [this post](http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/) for more information on breaking changes and new features available in this version.

```{r}
library(plotly)
packageVersion('plotly')
```

### Global Font Properties

```{r}
library(plotly)

t <- list(
  family = "sans serif",
  size = 14,
  color = 'blue')

p <- plot_ly(x=c(1,2,3,4,5), y=c(1,2,3,2,1)) %>%
  layout(title="Font Styling",
         font=t)


p
```

#Reference

See [https://plot.ly/r/reference/#layout-font](https://plot.ly/r/reference/#layout-font) for more information and options!