---
description: How to format axes of 3d plots in R with Plotly.
display_as: file_settings
language: r
layout: base
name: 3D Axes
order: 6
output:
  html_document:
    keep_md: true
page_type: u-guide
permalink: r/3d-axes/
thumbnail: thumbnail/theming-and-templates.png
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```


### Version Check

Version 4 of Plotly's R package is now [available](https://plot.ly/r/getting-started/#installation)!<br>
Check out [this post](http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/) for more information on breaking changes and new features available in this version.
```{r}
library(plotly)
packageVersion('plotly')
```

### Range of Axes

```{r}
library(plotly)

axx <- list(
  nticks = 4,
  range = c(-25,75)
)

axy <- list(
  nticks = 4,
  range = c(-25,75)
)

axz <- list(
  nticks = 4,
  range = c(0,50)
)

x <- 70*(runif(70, 0, 1))
y <- 55*(runif(70, 0, 1))
z <- 40*(runif(70, 0, 1))

p <- plot_ly(x = ~x, y = ~y, z = ~z, type = 'mesh3d') %>%
  layout(scene = list(xaxis=axx,yaxis=axy,zaxis=axz))

p
```

### Fixed Ratio Axes

```{r}
library(plotly)

# custom grid style
axx <- list(
  gridcolor='rgb(255, 255, 255)',
  zerolinecolor='rgb(255, 255, 255)',
  showbackground=TRUE,
  backgroundcolor='rgb(230, 230,230)'
)

# individual plots
p1 <- plot_ly(z = ~volcano, scene='scene1') %>%
  add_surface(showscale=FALSE)

p2 <- plot_ly(z = ~volcano, scene='scene2') %>%
  add_surface(showscale=FALSE)

p3 <- plot_ly(z = ~volcano, scene='scene3') %>%
  add_surface(showscale=FALSE)

p4 <- plot_ly(z = ~volcano, scene='scene4') %>%
  add_surface(showscale=FALSE)

# subplot and define scene
p <- subplot(p1, p2, p3, p4) %>%
  layout(title = "3D Subplots",
         scene = list(domain=list(x=c(0,0.5),y=c(0.5,1)),
                      xaxis=axx, yaxis=axx, zaxis=axx,
                      
                      # select the type of aspectmode
                      aspectmode='cube'),
         scene2 = list(domain=list(x=c(0.5,1),y=c(0.5,1)),
                       xaxis=axx, yaxis=axx, zaxis=axx,
                       aspectmode='data'),
         scene3 = list(domain=list(x=c(0,0.5),y=c(0,0.5)),
                       xaxis=axx, yaxis=axx, zaxis=axx,
                       aspectmode='auto'),
         scene4 = list(domain=list(x=c(0.5,1),y=c(0,0.5)),
                       xaxis=axx, yaxis=axx, zaxis=axx,
                       aspectmode='manual',
                       
                       # set your manual fixed aspect ratio
                       aspectratio = list(x=1, y=1, z=2)))

p
```

### Set Axes Title

```{r}
library(plotly)

axx <- list(
  title = "X AXIS TITLE"
)

axy <- list(
  title = "Y AXIS TITLE"
)

axz <- list(
  title = "Z AXIS TITLE"
)

x <- 70*(runif(70, 0, 1))
y <- 55*(runif(70, 0, 1))
z <- 40*(runif(70, 0, 1))

p <- plot_ly(x = ~x, y = ~y, z = ~z, type = 'mesh3d') %>%
  layout(scene = list(xaxis=axx,yaxis=axy,zaxis=axz))

p
```

### Ticks Formatting

```{r}
library(plotly)

axx <- list(
  ticketmode = 'array',
  ticktext = c("Huey", "Dewey", "Louie"),
  tickvals = c(0,25,50),
  range = c(-25,75)
)

axy <- list(
  nticks = 4,
  range = c(-25,75)
)

axz <- list(
  nticks = 4,
  range = c(0,50)
)

x <- 70*(runif(70, 0, 1))
y <- 55*(runif(70, 0, 1))
z <- 40*(runif(70, 0, 1))

p <- plot_ly(x = ~x, y = ~y, z = ~z, type = 'mesh3d') %>%
  layout(scene = list(xaxis=axx,yaxis=axy,zaxis=axz))

p
```

### Background and Grid Color

```{r}
library(plotly)

axx <- list(
  backgroundcolor="rgb(200, 200, 230",
  gridcolor="rgb(255,255,255)",
  showbackground=TRUE,
  zerolinecolor="rgb(255,255,255"
)

axy <- list(
  backgroundcolor="rgb(230, 200,230)",
  gridcolor="rgb(255,255,255)",
  showbackground=TRUE,
  zerolinecolor="rgb(255,255,255"
)

axz <- list(
  backgroundcolor="rgb(230, 230,200)",
  gridcolor="rgb(255,255,255)",
  showbackground=TRUE,
  zerolinecolor="rgb(255,255,255"
)

x <- 70*(runif(70, 0, 1))
y <- 55*(runif(70, 0, 1))
z <- 40*(runif(70, 0, 1))

p <- plot_ly(x = ~x, y = ~y, z = ~z, type = 'mesh3d') %>%
  layout(scene = list(xaxis=axx,yaxis=axy,zaxis=axz))

p
```

#Reference

See [https://plot.ly/r/reference/#layout-scene-xaxis](https://plot.ly/r/reference/#layout-scene-xaxis) for more information and options!