---
name: Dot Plots
permalink: r/dot-plots/
description: How to make a dot plot in R. Dot plots show changes between two points in time or between two conditions.
layout: base
thumbnail: thumbnail/dot-plot.jpg
language: r
display_as: basic
order: 14
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
# Dot and Dumbbell Plots

```{r}
library(plotly)

s <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/school_earnings.csv")
s <- s[order(s$Men), ]

fig <- plot_ly(s, x = ~Women, y = ~School, name = "Women", type = 'scatter',
             mode = "markers", marker = list(color = "pink"))
fig <- fig %>% add_trace(x = ~Men, y = ~School, name = "Men",type = 'scatter',
            mode = "markers", marker = list(color = "blue"))
fig <- fig %>% layout(
    title = "Gender earnings disparity",
    xaxis = list(title = "Annual Salary (in thousands)"),
    margin = list(l = 100)
  )

fig
```

#Reference

See [https://plot.ly/r/reference/#scatter](https://plot.ly/r/reference/#scatter) for more information and chart attribute options!
