---
description: How to make webGL based heatmaps in R with Plotly.
display_as: scientific
language: r
layout: base
name: WebGL Heatmaps
order: 13
output:
  html_document:
    keep_md: true
permalink: r/heatmap-webgl/
thumbnail: thumbnail/heatmap-webgl.jpg
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```



### Version Check

Version 4 of Plotly's R package is now [available](https://plot.ly/r/getting-started/#installation)!<br>
Check out [this post](http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/) for more information on breaking changes and new features available in this version.

```{r}
library(plotly)
packageVersion('plotly')
```

#### WebGL Heatmap from an Image

```{r}
library("jpeg")
library("plotly")

# Image processing
url <- "https://images.plot.ly/plotly-documentation/images/heatmap-galaxy.jpg"
tmpf <- tempfile()
download.file(url,tmpf,mode="wb")
data <- readJPEG(tmpf)
fr <- file.remove(tmpf) # remove the downloaded temp file

zdata = rowSums(data*255, dims = 2)

p <- plot_ly(
            z = zdata,
            colorscale = list(c(0,0.5,1),c("blue", "white", "red")),
            type = "heatmapgl"
            )

p
```

#### Reference

See [https://plot.ly/r/reference/#heatmapgl](https://plot.ly/r/reference/#heatmapgl) for more information and options!