---
description: How to add lighting effects in 3D R Plots.
display_as: file_settings
language: r
layout: base
name: 3D Surface Lighting in R
order: 9
output:
  html_document:
    keep_md: true
page_type: u-guide
permalink: r/3d-surface-lighting/
thumbnail: thumbnail/3d-surface-color.jpg
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Ambient

```{r}
library(plotly)

fig1 <- plot_ly(z = ~volcano, scene='scene1', lighting = list(ambient = 0.2)) 
fig1 <- fig1 %>%
  add_surface(showscale=FALSE)

fig2 <- plot_ly(z = ~volcano, scene='scene2', lighting = list(ambient = 0.9)) 
fig2 <- fig2 %>%
  add_surface(showscale=FALSE)

fig <-  subplot(fig1, fig2) 
fig <- fig %>%
  layout(title = "Ambient Lighting",
         grid = list(rows = 1, columns = 2,
                     pattern = 'independent'),
         scene = list(domain=list(column = 0),
                      aspectmode='cube'),
         scene2 = list(domain=list(column = 1),
                       aspectmode='cube'))

fig
```

### Roughness

```{r}
library(plotly)

fig1 <- plot_ly(z = ~volcano, scene='scene1', lighting = list(roughness = 0.1)) 
fig1 <-  fig1 %>%
  add_surface(showscale=FALSE)

fig2  <- plot_ly(z = ~volcano, scene='scene2', lighting = list(roughness = 0.9)) 
fig2 <-  fig2 %>%
  add_surface(showscale=FALSE)

fig <-  subplot(fig1, fig2) 
fig <- fig %>%
  layout(title = "Roughness",
         grid = list(rows = 1, columns = 2,
                     pattern = 'independent'),
         scene = list(domain=list(column = 0),
                      aspectmode='cube'),
         scene2 = list(domain=list(column = 1),
                       aspectmode='cube'))

fig
```

### Diffuse

```{r}
library(plotly)

fig1 <- plot_ly(z = ~volcano, scene='scene1', lighting = list(diffuse = 0.1)) 
fig1 <- fig1 %>%
  add_surface(showscale=FALSE)

fig2 <- plot_ly(z = ~volcano, scene='scene2', lighting = list(diffuse = 0.9)) 
fig2 <- fig2 %>%
  add_surface(showscale=FALSE)

fig <- subplot(fig1, fig2) 
fig <- fig %>%
  layout(title = "Diffuse Reflection",
         grid = list(rows = 1, columns = 2,
                     pattern = 'independent'),
         scene = list(domain=list(column = 0),
                      aspectmode='cube'),
         scene2 = list(domain=list(column = 1),
                       aspectmode='cube'))

fig
```

### Specular

```{r}
library(plotly)

fig1 <- plot_ly(z = ~volcano, scene='scene1', lighting = list(specular = 0.1)) 
fig1 <- fig1 %>%
  add_surface(showscale=FALSE)

fig2 <- plot_ly(z = ~volcano, scene='scene2', lighting = list(specular = 1.9)) 
fig2 <- fig2 %>%
  add_surface(showscale=FALSE)

fig <-  subplot(fig1, fig2) 
fig <- fig %>%
  layout(title = "Specular Reflection",
         grid = list(rows = 1, columns = 2,
                     pattern = 'independent'),
         scene = list(domain=list(column = 0),
                      aspectmode='cube'),
         scene2 = list(domain=list(column = 1),
                       aspectmode='cube'))

fig
```

### Fresnel

```{r}
library(plotly)

fig1 <- plot_ly(z = ~volcano, scene='scene1', lighting = list(fresnel = 0.1)) 
fig1 <-  fig1 %>%
  add_surface(showscale=FALSE)

fig2 <- plot_ly(z = ~volcano, scene='scene2', lighting = list(fresnel = 4.5)) 
fig2 <- fig2 %>%
  add_surface(showscale=FALSE)

fig <-  subplot(fig1, fig2) 
fig <- fig %>%
  layout(title = "Fresnel",
         grid = list(rows = 1, columns = 2,
                     pattern = 'independent'),
         scene = list(domain=list(column = 0),
                      aspectmode='cube'),
         scene2 = list(domain=list(column = 1),
                       aspectmode='cube'))

fig
```

#Reference

See [https://plot.ly/r/reference/#surface-lighting](https://plot.ly/r/reference/#surface-lighting) for more information and options!