---
description: How to set default trace colors using colorway in R with Plotly.
display_as: file_settings
language: r
layout: base
name: Colorway
order: 19
output:
  html_document:
    keep_md: true
page_type: u-guide
permalink: r/colorway/
thumbnail: thumbnail/colorway.jpg
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```



### Version Check

Version 4 of Plotly's R package is now [available](https://plot.ly/r/getting-started/#installation)!<br>
Check out [this post](http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/) for more information on breaking changes and new features available in this version.

```{r}
library(plotly)
packageVersion('plotly')
```

### Set Default Trace Colors with `colorway`

```{r}
library(plotly)

x <- seq(-1, 3, length=50)
ones <- rep(1, 50)
a_list <- seq(1, 3, length=7)
b_list <- seq(2, 14, length=7)
df <- data.frame(cbind(x, (outer((x*x), a_list) + outer(ones, b_list))))

p <- plot_ly(df, x = ~x, y = ~V2, type = 'scatter', mode = 'lines') %>%
  add_trace(y = ~V3) %>%
  add_trace(y = ~V4) %>%
  add_trace(y = ~V5) %>%
  add_trace(y = ~V6) %>%
  add_trace(y = ~V7) %>%
  add_trace(y = ~V8) %>%
  layout(colorway = c('#f3cec9', '#e7a4b6', '#cd7eaf', '#a262a9', '#6f4d96', '#3d3b72', '#182844'))


p
```

#Reference

See [https://plot.ly/r/reference/#layout-colorway](https://plot.ly/r/reference/#layout-colorway) for more information about the colorway attribute.