---
description: How to add WebGL text labels and annotations to plots in R.
display_as: file_settings
language: r
layout: base
name: WebGL Text and Annotations
order: 18
output:
  html_document:
    keep_md: true
page_type: u-guide
permalink: r/webgl-text-and-annotations/
thumbnail: thumbnail/webgl.jpg
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```
### Heatmap with Annotations

```{r}
library(plotly)
library(random)

n=250
t=12
x = c(rep(0:(n-1), times=t))
y = c(rep(0:(t-1), each=n))
z = randomNumbers(n=n*t, min=1, max=10, col=n)
text = c(replicate(t*n, sample(c("A","T","G","C"), 1)))

steps = list()
for (e in c(0:(n-30))){
  stefig <-  list(
    list(
      args = list('xaxis.range', c(-0.5 + e, 30.5 + e)),
      method = "relayout",
      label = e,
      value = e
    )
  )
  steps[e] <- step
}

fig <-  plot_ly() 
fig <- fig %>%
  add_trace(
    type='heatmap',
    z = z
  ) 
fig <- fig %>%
  add_trace(
    mode = "text",
    text = text,
    type = "scattergl",
    textfont = list(
      size = 20
    ),
    x = x,
    y = y
  ) 
fig <- fig %>%
  layout(
    xaxis = list(
      range = c(-0.5, 30.5),
      showline = F,
      zeroline = F,
      showgrid = F
    ),
    yaxis = list(
      showline = F,
      zeroline = F,
      showgrid = F
    ),
    sliders=list(
      list(
        active = 0,
        steps = steps
      )
    )
  )

fig
```

#Reference

See [https://plot.ly/r/reference/#scattergl](https://plot.ly/r/reference/#scattergl) for more information and chart attribute options!