---
name: 2D Histogram Contour
permalink: r/2d-histogram-contour/
description: How to create 2D Histogram Contour plots in R with Plotly.
layout: base
thumbnail: thumbnail/hist2dcontour.png
language: r
display_as: statistical
order: 7
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```



### Version Check

Version 4 of Plotly's R package is now [available](https://plot.ly/r/getting-started/#installation)!<br>
Check out [this post](http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/) for more information on breaking changes and new features available in this version.

```{r}
library(plotly)
packageVersion('plotly')
```

#### Basic 2D Histogram Contour

```{r}
library(plotly)

s <- matrix(c(1, -.75, -.75, 1), ncol = 2)
obs <- mvtnorm::rmvnorm(500, sigma = s)

p <- plot_ly(x = obs[,1], y = obs[,2]) %>% 
  add_trace(type='histogram2dcontour')

p
```

#### Styled 2D Histogram Contour

```{r}
library(plotly)

cnt <- with(diamonds, table(cut, clarity))

p <- plot_ly(diamonds, x = ~cut, y = ~clarity, z = ~cnt) %>%
  add_trace(
    type='histogram2dcontour',
    contours = list(
      showlabels = T,
      labelfont = list(
        family = 'Raleway',
        color = 'white'
      )
    ),
    hoverlabel = list(
      bgcolor = 'white',
      bordercolor = 'black',
      font = list(
        family = 'Raleway',
        color = 'black'
      )
    )
)

p
```

#### 2D Histogram Contour Subplot

```{r}
library(plotly)

x <- rnorm(1000)
y <- rnorm(1000)
s <- subplot(
  plot_ly(x = x, color = I("black"), type = 'histogram'), 
  plotly_empty(), 
  plot_ly(x = x, y = y, type = 'histogram2dcontour', showscale = F), 
  plot_ly(y = y, color = I("black"), type = 'histogram'),
  nrows = 2, heights = c(0.2, 0.8), widths = c(0.8, 0.2), 
  shareX = TRUE, shareY = TRUE, titleX = FALSE, titleY = FALSE
)

p <- layout(s, showlegend = FALSE)

p
```

#### Reference

See [https://plot.ly/r/reference/#histogram2dcontour](https://plot.ly/r/reference/#histogram2dcontour) for more information and options!
