---
name: Getting Started with Chart Studio
permalink: r/getting-started-with-chart-studio/
description: Get started with Chart Studio and Plotly's R graphing library.
page_type: example_index
layout: base
language: r
output:
  html_document:
    keep_md: true
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```

# Getting Started with Chart Studio and the `plotly` R Package

`plotly` is an R package for creating interactive web-based graphs via the open source JavaScript graphing library [plotly.js](http://plot.ly/javascript). 

As of version 2.0 (November 17, 2015), R graphs created with the `plotly` R package are rendered *locally* through the [htmlwidgets](http://www.htmlwidgets.org/) framework.

#### Initialization for Online Plotting

You can choose to publish charts you create with the `plotly` R package to the web using the Chart Studio web service.

1 - [Create a free Chart Studio account](https://plot.ly/api_signup):<br>
A Chart Studio account is required to publish R charts with Chart Studio. It's free to get started, and you control the privacy of your charts.

2 - Save your authentication credentials<br>
Find your authentication API keys [in your online settings](https://plot.ly/settings/api). Set them in your R session with:

```r
Sys.setenv("plotly_username"="your_plotly_username")
Sys.setenv("plotly_api_key"="your_api_key")
```

Save these commands in your [.Rprofile](http://www.statmethods.net/interface/customizing.html) file to be run every time you start R.

3 - Publish your graphs to Chart Studio with `api_create`

Use the `filename` attribute to set the title of the file that will be generated in your Chart Studio account.

```r
library(plotly)
p <- plot_ly(midwest, x = ~percollege, color = ~state, type = "box")
api_create(p, filename = "r-docs-midwest-boxplots")
```

4 (optional) - Suppress auto open

When following the instructions above, `api_create(p)` will auto open the created URL in the browser. To suppress this behavior, set the `browser` option to `false` in your R session:

```r
options(browser = 'false')
api_create(p, filename = "r-docs-midwest-boxplots")
```

#### Special Instructions for Chart Studio Enterprise Users

Your API key for account on the public cloud will be different than the API key in [Chart Studio Enterprise](https://plot.ly/product/enterprise/). 

Visit <https://plotly.your-company.com/settings/api/> to find your Chart Studio Enterprise API key. 

Remember to replace "your-company.com" with the URL of your Chart Studio Enterprise server.

If your company has a Chart Studio Enterprise server, then you need to change the R API endpoint so that it points to your company's Chart Studio Enterprise.

In your .RProfile, write:

```r
Sys.setenv("plotly_domain"="https://plotly.your-company.com")
```

Remember to replace "your-company" with the URL of your Chart Studio Enterprise server.

<div class="row centered btnrow">
    <a href="/r/" class="button no_underline">Make your first graph</a>
</div>

#### Chart Studio Plot Privacy Modes

Chart Studio plots can be set to three different type of privacy modes: `public`, `private`, or `secret`.

* **public:**

     Anyone can view this graph. 
     It will appear in your Chart Studio profile and can be indexed by search engines. 
     Being logged in to a Chart Studio account is not required to view this chart.

* **private:**

     Only you can view this plot. 
     It will not appear in the public Chart Studio feed, your Chart Studio profile, or be indexed by search engines. 
     Being logged into your Chart Studio account is required to view this graph. 
     You can privately share this graph with other Chart Studio users. They will also need to be logged in to their Chart Studio account to view this plot. 
     This option is only available to Chart Studio Enterprise subscribers.

* **secret:**

     Anyone with this secret link can view this chart. 
     It will not appear in the public Chart Studio feed, your Chart Studio profile, or be indexed by search engines. 
     If it is embedded inside a webpage or an IPython notebook, anybody who is viewing that page will be able to view the graph. 
     You do not need to be logged in to your Chart Studio account view this plot. 
     This option is only available to Chart Studio Enterprise subscribers.

By default all Chart Studio plots you create with the `plotly` R package are set to `public`. Users with free Chart Studio accounts are limited to creating `public` plots. 

If you have private storage needs, please learn more about [Chart Studio Enterprise](https://plot.ly/online-chart-maker/). 

If you're a [Chart Studio Enterprise subscriber](https://plot.ly/settings/subscription/?modal=true&utm_source=api-docs&utm_medium=support-oss) and would like the setting for your plots to be private, you can specify sharing as private:

```r
api_create(filename = "private-graph", sharing = "private")
```
For more information regarding the privacy of plots published to Chart Studio using the `plotly` R package, please visit [our Chart Studio privacy documentation](https://plot.ly/r/privacy/)
